### ISSUE TITLE
Use your own custom salt

### ISSUE THREAD

**Issue by p91** [pyca/bcrypt#13]
Hi,

I want to use bcrypt in a challenge response scheme.
For this, I need a way to set the salt myself (the idea is that the salt is the challenge given)
With PHP, this was not a problem but I do not understand how this is done here.
AFAIK the salt for a bcrypt hash should be 16 random bytes. How can I us my own salt with bcrypt in python?

with best regards,

p91

**Comment by reaperhulk** [comment]
The scheme of a salt is pretty straightforward and is documented elsewhere. People who wish to do this can build their own salt outside of this library and then feed the salt to `hashpw`.
