### ISSUE TITLE
Change bcrypt's tagline?

### ISSUE THREAD

**Issue by reaperhulk** [pyca/bcrypt#131]
Current tag is "Modern password hashing for your software and your servers" but we should be recommending scrypt over bcrypt (and in the future potentially argon2id).

**Comment by dstufft** [comment]
Sort of modern password hashing for your software and your servers?

**Comment by reaperhulk** [comment]
"Not incredibly outdated" 😀

**Comment by roycewilliams** [comment]
At authentication-at-scale-with-good UX speeds, (<0.1s), bcrypt may be more resistant to cracking than scrypt or Argon2, as per @Sc00bz' note [here](https://twitter.com/Sc00bzT/status/981166657899978758). Only when your users can tolerate -- and your infrastructure can handle -- authentication delays of one second or more do scrypt or Argon2 start to look better (according to his testing). YMMV.
