### ISSUE TITLE
checkpw is missing/cannot be found

### ISSUE THREAD

**Issue by dylanlegg** [pyca/bcrypt#140]
Using version 3.1.4 with python 2.7.13 all on Debian 9 and the checkpw function cannot be found. Installed manually, using pip and through my compiler, but I still can't get it working. 
All dependencies are installed as per your instructions and I've tried rolling back to 3.1.0 but I still get the same error.

**Comment by dylanlegg** [comment]
Should note: It has worked in the past but after some various update it suddenly stopped working - even after all updates were rolled back.

**Comment by reaperhulk** [comment]
Create a new virtualenv and see if it works inside that. If it does, the most likely scenario is that there's some older version of bcrypt lurking in your python path that's being loaded and causing this problem for you.

**Comment by dylanlegg** [comment]
Feeling foolish - there was a completely different bcrypt package installed that was using the same filenames/directory structure as this that was clashing. Not-a-real-issue resolved!
