### ISSUE TITLE
Python 3.7 issue

### ISSUE THREAD

**Issue by josephmancuso** [pyca/bcrypt#142]
@Alex @reaperhulk Hey, me again :(

I was just talking to you guys in the cryptography repo. 

so bcrypt doesn't install even standalone on Python 3.7-dev:

https://travis-ci.org/josephmancuso/test-repo/builds/370139321

**Comment by alex** [comment]
This looks like it's the same "ValueError: bad marshal data (unknown type code)" error from pycparser as we saw on cryptography.

Can you confirm if the same workaround works?

**Comment by josephmancuso** [comment]
the workaround was the install it by itself which I did.

**Comment by josephmancuso** [comment]
casually browsing the Python 3.7 change log and found:

https://docs.python.org/3.7/reference/import.html#cached-bytecode-invalidation

I'm not sure what pycparser does but there were changes to pyc files. This could be completely irrelevant

**Comment by josephmancuso** [comment]
looking through my build history, I used to have 3.7-dev build but it randomly started failing one day: https://travis-ci.org/MasoniteFramework/masonite/builds/333092967

That might be good to get a time frame of when it started failing against 3.7-dev. It started failing 3 months ago so I just removed it and chalked it up to a non backwards compatible push for the next release of Python. Might be worth while to match the date to the change log

**Comment by josephmancuso** [comment]
Ok I'll try to get an answer to them. Thanks again!
