### ISSUE TITLE
Support base64-encoding 24 bytes instead of 23

### ISSUE THREAD

**Issue by gpip** [pyca/bcrypt#144]
bouncycastle (java) encodes the 24 bytes and ignores the compatibility-bug conformance with openbsd's implementation. Would you consider doing the same here? The c lib could just return the bytes as is, and the python func could decide whether to return the truncated encoded output or the full output.

**Comment by reaperhulk** [comment]
I'm not sure I follow. From a quick look it appears that BC's bcrypt support handles $2b style hashing, which this library supports. What is the actual difference in implementations?

**Comment by gpip** [comment]
https://github.com/pyca/bcrypt/blob/master/src/_csrc/bcrypt.c#L163 where it reads

```
encode_base64(encrypted + 7 + 22, ciphertext, 4 * BCRYPT_WORDS - 1);
```

would become

```
encode_base64(encrypted + 7 + 22, ciphertext, 4 * BCRYPT_WORDS);
```

**Comment by gpip** [comment]
or, another way, would be to return the raw data and encode/decode with the custom base64 in python. So you would have the choice between: a) getting raw data, b) getting truncated base64 output, c) getting full base64 output (i.e. 24 bytes instead of 23)

**Comment by reaperhulk** [comment]
Okay, and BouncyCastle doesn't truncate/has no way to truncate to be compatible with the OpenBSD style? Adding additional output types to this library isn't something I want to see us do without a very good reason so I want to be sure I understand what the interoperability story is right now.

**Comment by gpip** [comment]
Right, it doesn't, it's always the 24 bytes. They also don't do any of the custom base64 encoding used by openbsd's bcrypt, but that's easier to workaround.

**Comment by reaperhulk** [comment]
Okay, I understand now. This library is intended to be a drop-in replacement for the OpenBSD bcrypt including its serialization format. BC implements a core bcrypt that doesn't quite follow that spec, but it also has OpenBSDBCrypt (https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/generators/OpenBSDBCrypt.java) so I think that's the appropriate workaround for cross-compatibility here.

**Comment by gpip** [comment]
If there was some way to recover the lost byte I would agree, but there isn't. You cannot make this compatible with any other users of bouncycastle's bcrypt.
