### ISSUE TITLE
Release wheels compatible with Python 3.7

### ISSUE THREAD

**Issue by jaraco** [pyca/bcrypt#148]
You probable saw this coming. It would be nice to have binary releases cut for Python 3.7.

**Comment by reaperhulk** [comment]
yep this will be taken care of shortly. And we’ll be switching to limited api wheels on macOS and Linux to limit the scope of future issues as well

**Comment by reaperhulk** [comment]
Done for both py 3.7 and limited api, thanks for the reminder!
