### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by k3it** [pyca/bcrypt#160]
just checking if there are plans to make an updated pypi release.  looks like there have been a few changes after 3.1.4.

**Comment by reaperhulk** [comment]
Looks like our changes since 3.1.4 are the AIX fix you contributed, dropping py2.6/py3.3, and some packaging updates. I can run a release today assuming no unexpected obstacles.

**Comment by reaperhulk** [comment]
3.1.5 is released

**Comment by k3it** [comment]
Thanks, I appreciate it.  made it easier to install on systems via pip!
