### ISSUE TITLE
Release v3.1.7

### ISSUE THREAD

**Issue by webknjaz** [pyca/bcrypt#172]

**Comment by reaperhulk** [comment]
Is this just for the setuptools lower bound?

**Comment by webknjaz** [comment]
yes

**Comment by webknjaz** [comment]
Ref: https://github.com/pyca/bcrypt/pull/171#issuecomment-490214142

**Comment by webknjaz** [comment]
The thing is that because of bugs in Pip's build virtualenv isolation the PEP517 build backend hits setuptools from system site-packages and it's usually old. I hope that this will fix the issue.

**Comment by shanemcd** [comment]
+1, our builds are failing because of this. Can we get a new release?

**Comment by reaperhulk** [comment]
Done!
