### ISSUE TITLE
ImportError , DLL load failed

### ISSUE THREAD

**Issue by zlc-zy** [pyca/bcrypt#186]
OS: windows server 2008 R2
bcrypt: 3.1.4
python: 3.5.1

when I import bcrypt,  I get an error,  any advices ?

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "..\site-packages\bcrypt\__init__.py",
 line 25, in <module>
    from bcrypt import _bcrypt
ImportError: DLL load failed:

**Comment by reaperhulk** [comment]
Upgrade to latest pip and install the latest bcrypt into a fresh virtualenv and see if you still get the same error.

**Comment by zlc-zy** [comment]
I fixed by installing vc_redist.x86.exe  https://www.microsoft.com/en-us/download/details.aspx?id=48145
