### ISSUE TITLE
Allow passing password and hashed_password as strings (unicode) not bytes

### ISSUE THREAD

**Issue by retnikt** [pyca/bcrypt#194]
Could we allow passing of passwords, salts, and hashes as normal strings rather than encoded bytes? Currently if they are passed to `checkpw` and `hashpw` a TypeError is thrown. Could we not just automatically encode them? (maybe not the salt) Since the hash is already in base64 (so contains no special characters), and no-one in their right mind would allow control characters in a password, there is no need, especially in a Python 3 world, to use bytes. (This may also be representative of a need to drop Python 2 (ewww) compatibility).

**Comment by alex** [comment]
The underlying algorithms are defined in terms of bytes. Any choice of encoding we chose would introduce the possibility of interoperability challenges, or encoding mistakes.
