### ISSUE TITLE
checking a pre-hashed password.

### ISSUE THREAD

**Issue by samuelcolvin** [pyca/bcrypt#204]
(sorry to create the issue without a description)

I need a way to hash a password in one step and check it in another, effectively splitting `checkpw` in two.

Question: is `secrets.compare_digest(ret, hashed_password)` safe to use as an equivalent to

```py
    if len(ret) != len(hashed_password):
        return False

    return _bcrypt.lib.timingsafe_bcmp(ret, hashed_password, len(ret)) == 0
```

?

If not, would it be possible to expose the above or just `_bcrypt.lib.timingsafe_bcmp` as a public function?

---

Use cases:
1. MFA on a separate page from username and password, but then checking password and MFA in the same request. Here I want to either add the password hash to the session or return it as a hidden field in the MFA form, then check it later
2. on a multi-tenant system where someone could in theory have the same email address associated with multiple accounts, you quite often need to split authentication into multiple steps:
  * enter email and password
  * offer a choice of accounts where that email address is valid
  * validate the password against the hash stored with the email address for the selected account
3. Timing attack to check if an account exists to see if an account with the given identifier exists but checking whether the request is slow because password hashing takes place. Here it would be very useful to always hash the password, even if the user doesn't exist.

In both case 1. and 2. the password checking happens multiple steps after entering the password; but I want to hash the password so it's safe(r) to store than the password itself.

**Comment by charmander** [comment]
Details?

**Comment by samuelcolvin** [comment]
While writing the issue, I've realised what I'm asking for is impossible since the need to know the target hash to hash the proposed password.

I'd love your suggestions for an alternative way around this group of questions, but I'll close this as overall I realise it makes little to no sense 🙈.
