### ISSUE TITLE
checkpw: internal code explanation

### ISSUE THREAD

**Issue by lewoudar** [pyca/bcrypt#205]
Hi guys,
This is not an issue but I don't know if there is  a forum discussion so I state my problem here. I wonder what this [line](https://github.com/pyca/bcrypt/blob/master/src/bcrypt/__init__.py#L112) of code does.
I check the C code of `timingsafe_bcmp` but I'm not an expert in C programming ^^

**Comment by reaperhulk** [comment]
```c
int
timingsafe_bcmp(const void *b1, const void *b2, size_t n)
{
	const unsigned char *p1 = b1, *p2 = b2;
	int ret = 0;

	for (; n > 0; n--)
		ret |= *p1++ ^ *p2++;
	return (ret != 0);
}
```

What this does is iterate over each byte in b1 and b2, XOR them against each other, and OR them into the return value. This does a comparison between two byte strings (of equal length only!) in a constant-time fashion. That is to say, it will take the same amount of time no matter where the strings become unequal.

**Comment by lewoudar** [comment]
thanks for explaining
