### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [pyca/bcrypt#206]
**Summary**
Installing bcrypt on aarch64 via pip using command "pip3 install bcrypt" tries to build wheel from source code

**Problem description**
bcrypt don't have wheel for aarch64 on PyPI repository. So, while installing bcrypt via pip on aarch64, pip builds wheel for same resulting in it takes more time to install bcrypt. Making wheel available for aarch64 will benefit aarch64 users by minimizing bcrypt installation time.

**Expected Output**
Pip should be able to download bcrypt wheel from PyPI repository rather than building it from source code.

@bcrypt-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make bcrypt wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by reaperhulk** [comment]
Unlike pyca/cryptography we can definitely add aarch64 wheel support easily here. If you'd like to contribute a PR that adds an aarch64 travis builder that's the first step. After that we need to figure out how to add aarch64 wheel builds to our automated system which is currently triggered within github actions...which does not support aarch64 unfortunately.

**Comment by odidev** [comment]
@reaperhulk, thanks for the quick response. I am working on it.

**Comment by odidev** [comment]
Ping @reaperhulk 
I have raised a PR for adding arm64 jobs in travis CI. #207 
Please review and suggest if any changes are required.

Also,please let me know about the next step.

Thanks

**Comment by odidev** [comment]
Hi @reaperhulk ,

Thanks for reviewing and merging the PR.
Please let me know if any help is required from our side to add wheel support for aarch64.

Thanks

**Comment by reaperhulk** [comment]
I think qemu on GHA is probably the easiest path there. It lets us reuse the existing infrastructure and automation. If you want to experiment with making a qemu-based action that can build a wheel that's likely to be fruitful. It looks like there are some pre-existing actions for docker-based qemu work too.

**Comment by odidev** [comment]
Hi @reaperhulk ,
Thank you for the suggestion. We will work on it and update about findings.

**Comment by odidev** [comment]
Hi @reaperhulk ,

I have added arm64 jobs to workflows using qemu for building arm64 wheels. Please check below links for updated workflows and wheel build:

Changes for wheel creation:
**Script** : https://github.com/odidev/bcrypt/blob/master/.github/workflows/wheel-builder.yml
           https://github.com/odidev/bcrypt/blob/master/.github/scripts/arm64_create_wheels.sh
**Github-action report** : https://github.com/odidev/bcrypt/actions/runs/185682479

The wheel is generated for all the python version successfully in arm64.

Result :
Added 3 test jobs for arm64 wheel. Please find the list below:
Arm64 wheel-python3.6 succeeded (0 annotations)
Arm64 wheel-python3.7 succeeded (0 annotations)
Arm64 wheel-python3.8 succeeded (0 annotations)

 Can I raise a PR with these changes or any other changes are required? Please give your feedback.

Thanks

**Comment by reaperhulk** [comment]
Thanks for your work on this! However, we need the images to be built using `quay.io/pypa/manylinux2014_aarch64` so that we get manylinux compatible wheels at the end. Just supplying the plat_name is insufficient due to linking against newer glibc, etc on newer platforms. You can follow the existing manylinux. Additionally, we can generate just a single abi3 wheel. You can follow the existing manylinux example to see how to do that.

**Comment by reaperhulk** [comment]
Done and uploaded
