### ISSUE TITLE
Adding type hints

### ISSUE THREAD

**Issue by sbdchd** [pyca/bcrypt#215]
I was wondering if you'd be open to adding type hints to the repo.

Since the project is compatible with python 2.7 it would need either [comment based types](https://mypy.readthedocs.io/en/stable/python2.html) or separate stub files.

**Comment by reaperhulk** [comment]
I would be very interested in type hints, but as you noted they're less pleasant in 2.7. It would be interesting to discuss whether 2.7 support should be dropped sooner to gain the advantage of inline type hinting. In general I'd be in favor of that, although I think we'd want to do one last 2.7 compatible release.

**Comment by sbdchd** [comment]
Also need to bump the minimum python 3 version from 3.5 to 3.6 for https://www.python.org/dev/peps/pep-0526/

**Comment by reaperhulk** [comment]
For the last month here are the download stats for 3.1.7 (latest):
<img width="247" alt="image" src="https://user-images.githubusercontent.com/161495/89963055-2c597580-dc0c-11ea-8da9-2b4ddca9749a.png">

That's 8,712,189 downloads for the top 5, with 2.7 making up 17.4% of the downloads and 3.5 being an additional 5.6%.

Despite the relatively high level of 2.7 usage we're still going to drop it soon due maintenance burden as more and more of our deps drop support. 3.5 may also be a reasonable candidate to drop in the semi-near future. I believe the primary 3.5 users are on Ubuntu 16.04 (official EOL April 2021) and Debian oldstable (stretch). Both of whom should upgrade or can pin to older versions of this package.

I think I'm in favor of using `bcrypt` as our guinea pig for this transition. It's a lower risk package and pinning older versions is less problematic than `cryptography`. PRs may be incoming shortly to make this doable :)

**Comment by reaperhulk** [comment]
...done. Okay, 3.6 minimum for the next release. I look forward to seeing that type hinting :smile:
