### ISSUE TITLE
whl packages for Python 3.7/8 are not available on pypi

### ISSUE THREAD

**Issue by Costya-Y** [pyca/bcrypt#227]
Hello,

It appears the only whl package on pypi was assembled for python 3.6 and doesn't work for 3.7/3.8.
Can you please upload appropriate whl packages to pypi?

Thank you,
Costya

**Comment by alex** [comment]
We now build ABI3 wheels for bcrypt on macOS, Linux, and Windows. See for details:

https://cryptography.io/en/latest/faq/#why-are-there-no-wheels-for-python-3-6-on-linux-or-macos

**Comment by Costya-Y** [comment]
Got it. Thank you @alex
