### ISSUE TITLE
cannot gensalt prefix for $2y$

### ISSUE THREAD

**Issue by duronrulez** [pyca/bcrypt#233]
How do i get a $2y$ output from the hashing?

```
salt = bcrypt.gensalt(prefix=b'2y',rounds=9)
hash = bcrypt.hashpw(b'123123', salt)
print(hash)
```
This throws and exception 
```
Supported prefixes are b'2a' or b'2b'"
```

If i omit the prefix i get a $2b$ hash. Is there a way to get a $2y$ hash?

Using version 3.2.0

**Comment by reaperhulk** [comment]
You can only verify 2y hashes, not generate them. However, that identifier is identical to a 2b hash so you can just change it yourself.
