### ISSUE TITLE
Determine which prefix we should use

### ISSUE THREAD

**Issue by dstufft** [pyca/bcrypt#25]
bcrypt has had a sort of sordid history with prefixes. The original one was ``$2a$`` however the original implementation had a security sensitive issue. This is fixed and ``$2a$`` is safe now assuming the implementation has been updated (for bcrypt it has been). However the bcrypt library we use also supports ``$2y$`` which is the same as ``$2a$`` except it'll fail on older libraries which are still broken (or which just don't suport the ``$2y$`` syntax. Now there's a new version of the crypt_blowfish library which implements ``$2b$`` which is the same as ``$2y$`` except it's "more official" since it comes from OpenBSD 5.5+.

**Comment by xhub-com** [comment]
I'm currently implementing bcrypt password usage in a project and wanted to drop my two cents after reading through jazzyb's changes. The hashes in my system are accessed both by Python and PHP. Where $2y$ is the indicator that it is using the patched $2a$, should not $2y$ be the default output, with $2b$ as an option? Right now, $2a$ and $2y$ are supported by the 'stable' PHP 5.5 library, where $2b$ is not. If $2b$ is algorithmically the same as $2y$, would it be better to stay compatible? And later updating the default to $2b$ when it is better supported?

    php > $pwd = 'hello world';
    php > $hasha = '$2a$12$CPeaPhxqTrBzJXP1KB1C/.t.2TJ7EzHhyCCmiLKAEKZovzmvdMwge';
    php > $hashb = '$2b$12$CPeaPhxqTrBzJXP1KB1C/.t.2TJ7EzHhyCCmiLKAEKZovzmvdMwge';
    php > $hashy = '$2y$12$CPeaPhxqTrBzJXP1KB1C/.t.2TJ7EzHhyCCmiLKAEKZovzmvdMwge';
    bool(false)
    php > var_dump(password_verify($pwd, $hasha));
    bool(true)
    php > var_dump(password_verify($pwd, $hashb));
    bool(false)
    php > var_dump(password_verify($pwd, $hashy));
    bool(true)

**Comment by xhub-com** [comment]
I'm adding a check in my code to handle this issue if $2b$ becomes the default, but had I not seen this post, I would have had a lot of very unhappy users.
