### ISSUE TITLE
Not able to install bcrypt library using the .gz file in linux environment.

### ISSUE THREAD

**Issue by unikill066** [pyca/bcrypt#270]
I have the necessary requirements installed like setuptools, cffi and six libraries(s), despite that the installation is failing. As you can see from the below error, during installation, internally it is trying to connect to pypi.org, how to get around this issue and install bcrypt library locally with the .tar.gz file available ?

  ---------------- Error ------------------
(venv) [user@server Libraries]$ pip install bcrypt-3.2.0.tar.gz
Processing ./bcrypt-3.2.0.tar.gz
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/Downloads/venv/bin/python3 /home/user/Downloads/venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-e85jbr5q/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel 'cffi>=1.1; python_implementation != '"'"'PyPy'"'"''
       cwd: None
  Complete output (7 lines):
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fda0d814ed0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fda08afa410>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fda08afa510>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fda08afa690>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fda08afa7d0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
  ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
  ERROR: No matching distribution found for setuptools>=40.8.0
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/user/Downloads/venv/bin/python3 /home/user/Downloads/venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-e85jbr5q/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel 'cffi>=1.1; python_implementation != '"'"'PyPy'"'"'' Check the logs for full command output.
  ----------------------------------------

Thanks, Nikhil

**Comment by reaperhulk** [comment]
This is a `pip` question and not related to bcrypt since it's about generic offline install. You'll want things like `--no-index` and `--find-links` but you'll need to consult the `pip` documentation .
