### ISSUE TITLE
It's 2022: async/await should be the first/recommended way to use the library

### ISSUE THREAD

**Issue by machineghost** [pyca/bcrypt#349]
When you read https://www.npmjs.com/package/bcrypt you get a massive wall of text of all the wrong (or at least, old) ways of using the library.  Then after you've finally waded through all of that, you finally get to the right way ... and it's not even documented fully!  You just have one example (not full documentation) on how to use `async`/`await`.

But it's 2022!  `async`/`await` isn't some crazy new syntax: it's standard JS development.

So why not _start_ with the way that a modern web developer would use the library, instead of starting with all the wrong/out-of-date ways?

**Comment by alex** [comment]
this is a python package, it has nothing to do with npm.

**Comment by machineghost** [comment]
Whoops, wrong project; apologies!
