### ISSUE TITLE
Precompiled ARM package in pip?

### ISSUE THREAD

**Issue by Blackbox-git** [pyca/bcrypt#409]
Hello all,

I just tried to install Paramiko on a Raspberry Pi via pip.

Paramiko requires bcrypt. Now my dilemma starts. When I install rustc via apt, I get the error message that rustc is only available in version 1.48 but 1.56 is required.

Do I really have to compile rustc from source myself or can you provide a precompiled ARM package in pip?

Greetings Stefan

**Comment by reaperhulk** [comment]
Unfortunately GitHub Actions provides no CI to generate or test 32-bit `armhf` packages so we don't really have a good way  to do this. There are two paths available here:

1) If you're on a rpi 3/4 you can actually install a 64-bit Linux distribution (including the latest raspbian) which is compatible with the wheels we do upload.
2) You can install a newer rust via [rustup](https://rustup.rs) and compile bcrypt using that, which is probably a much simpler solution :smile:

**Comment by reaperhulk** [comment]
Unfortunately GitHub Actions provides no CI to generate or test 32-bit `armhf` packages so we don't really have a good way  to do this. There are two paths available here:

1) If you're on a rpi 3/4 you can actually install a 64-bit Linux distribution (including the latest raspbian) which is compatible with the wheels we do upload.
2) You can install a newer rust via [rustup](https://rustup.rs) and compile bcrypt using that, which is probably a much simpler solution :smile:

**Comment by Blackbox-git** [comment]
Thanks for your tips. I will try the second option.

My project is so complex that I have so far shied away from the effort to migrate it to 64bit.

Besides, it is currently running on an old RPI2 and RPI4, which support 64bit are few and far between. I hope my English is not too bad.

Good time

**Comment by Blackbox-git** [comment]
Hello, 
I have tried the second suggestion from you. The installation of rustup has also been done without errors.

If I now try to install bcrypt via pip3, however, I run again on the error that rustc should not be present. 

```
 =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install bcrypt:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Ensure you have a recent Rust toolchain installed. bcrypt requires
         rustc >= 1.56.0.

      Python: 3.9.2
      platform: Linux-5.15.61-v7+-armv7l-with-glibc2.31
      pip: n/a
      setuptools: 65.3.0
      setuptools_rust: 1.5.1
      rustc: n/a
      =============================DEBUG ASSISTANCE=============================
```


I am not really a programmer, can you tell me what I am doing wrong?

**Comment by reaperhulk** [comment]
That sounds like you installed rust via rustup but didn't complete the installation by modifying your shell to initialize the PATH properly (or else when you're compiling you're not using the same shell PATH). What do you get if you type `rustc --version` in your shell? If it's nothing, run through the rustup installation process again and verify that your shell init is being changed. If it isn't nothing, then run `which rustc` (which will probably output something like `/home/youruser/.cargo/bin/rustc`) and then try installing with `PATH=/home/youruser/.cargo/bin:$PATH pip install bcrypt` where the PATH is the bin dir you see in `which`.
