### ISSUE TITLE
Invalid work factors are not handled cracefully

### ISSUE THREAD

**Issue by hrantzsch** [pyca/bcrypt#416]
bcrypt 4.0.0 doesn't seem to handle invalid work factor values well. The rust backend just panics:

```
>>> import bcrypt
>>> bcrypt.checkpw("password".encode(), "$2b$3$mdEQPMOtfPX.WGZNXgF66OhmBlOGKEd66SQ7DyJPGucYYmvTJYviy".encode())
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: CostNotAllowed(3)', src/lib.rs:52:87
Traceback (most recent call last):
  ...
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: CostNotAllowed(3)
```

This applies to work factors smaller than 4 and larger than 31.

Previous versions raised a `ValueError("Invalid salt")`, which is what I would have expected.

**Comment by alex** [comment]
Yes, this indeed looks like a bug.

**Comment by hrantzsch** [comment]
That was very quick. Thanks!
