### ISSUE TITLE
Document OS X installation

### ISSUE THREAD

**Issue by jbolda** [pyca/bcrypt#42]
Note: Issue exists on bcrypt as well.

@reaperhulk: "We implicitly assume our OS X users already have a compiler and the ffi headers (xcode-select --install). This is sometimes an unsafe assumption, especially as our project gets more popular. Let's document how to install on OS X."

The specific error code snippet is below. It fails on the cffi dependency.

```
c/_cffi_backend.c:13:10: fatal error: 'ffi.h' file not found

#include <ffi.h>

         ^

1 error generated.

error: command 'cc' failed with exit status 1
```

Reproduced from: https://github.com/pyca/cryptography/issues/1700

**Comment by dstufft** [comment]
Since bcrypt and cffi both release wheels, do we still need to do this? Folks installing with an up to date pip no longer need a compiler by default on macOS.
