### ISSUE TITLE
Can't install on PyPy

### ISSUE THREAD

**Issue by remram44** [pyca/bcrypt#434]
It seems that there are no binary wheels for PyPy, and build from source now requires a Rust toolchain. This is a major problem for installation.

```
$ docker run -ti --rm pypy:3.9 bash

/# pip install -U pip
Successfully installed pip-22.2.2

/# pip install bcrypt
Collecting bcrypt
  Downloading bcrypt-4.0.0.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: bcrypt
  Building wheel for bcrypt (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for bcrypt (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-pypy39
      creating build/lib.linux-x86_64-pypy39/bcrypt
      copying src/bcrypt/__about__.py -> build/lib.linux-x86_64-pypy39/bcrypt
      copying src/bcrypt/__init__.py -> build/lib.linux-x86_64-pypy39/bcrypt
      running egg_info
      writing src/bcrypt.egg-info/PKG-INFO
      writing dependency_links to src/bcrypt.egg-info/dependency_links.txt
      writing requirements to src/bcrypt.egg-info/requires.txt
      writing top-level names to src/bcrypt.egg-info/top_level.txt
      reading manifest file 'src/bcrypt.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files found matching 'requirements.txt'
      warning: no previously-included files found matching 'release.py'
      warning: no previously-included files found matching 'mypy.ini'
      warning: no previously-included files matching '*' found under directory '.github'
      warning: no previously-included files matching '*' found under directory '.circleci'
      warning: no previously-included files found matching 'src/_bcrypt/target'
      warning: no previously-included files matching '*' found under directory 'src/_bcrypt/target'
      adding license file 'LICENSE'
      writing manifest file 'src/bcrypt.egg-info/SOURCES.txt'
      copying src/bcrypt/_bcrypt.pyi -> build/lib.linux-x86_64-pypy39/bcrypt
      copying src/bcrypt/py.typed -> build/lib.linux-x86_64-pypy39/bcrypt
      running build_ext
      running build_rust
      
          =============================DEBUG ASSISTANCE=============================
          If you are seeing a compilation error please try the following steps to
          successfully install bcrypt:
          1) Upgrade to the latest pip and try again. This will fix errors for most
             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
          2) Ensure you have a recent Rust toolchain installed. bcrypt requires
             rustc >= 1.56.0.
      
          Python: 3.9.12
          platform: Linux-5.15.0-48-generic-x86_64-with-glibc2.31
          pip: n/a
          setuptools: 65.4.1
          setuptools_rust: 1.5.2
          rustc: n/a
          =============================DEBUG ASSISTANCE=============================
      
      error: can't find Rust compiler
      
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      
      To update pip, run:
      
          pip install --upgrade pip
      
      and then retry package installation.
      
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      
      This package requires Rust >=1.56.0.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bcrypt
Failed to build bcrypt
ERROR: Could not build wheels for bcrypt, which is required to install pyproject.toml-based projects
```

Installing 3.2.2 works.

**Comment by alex** [comment]
Have you tried installing rust? What problems did you encounter?

**Comment by remram44** [comment]
That's not my point. If the authors are fine with users of a common, supported platform needing to install Rust to use their module, they may close this issue.

**Comment by alex** [comment]
To lay my cards on the table: I'm a long time PyPy core developer, so I'd
very much like it to be better supported.

However, it is not widely used ATM, well under 1% of our downloads when I
last looked.


We'll consider adding wheel support --* we ship them for pyca/cryptography,
but it's painful due to the lack of a stable ABI.


בתאריך יום ה׳, 6 באוק׳ 2022, 10:13, מאת Remi Rampin ‏<
***@***.***>:

**Comment by remram44** [comment]
I don't think my own code has many PyPy users, but as this is my only dependency that doesn't install on PyPy, I will just lock `bcrypt<4`.

For anyone else finding this, `hashlib.pbkdf2_hmac()` is a good solution available in the standard library since Python 3.4.

**Comment by reaperhulk** [comment]
Just to be clear, `pbkdf2_hmac` is a *bad* solution. `hashlib.scrypt` is a better solution than `bcrypt` and is included in the stdlib since 3.6 though.

**Comment by remram44** [comment]
Even better, somehow I had missed the inclusion of scrypt in the standard library. Thanks!

Either way, removing bcrypt would prevent users from logging in to my app with their existing passwords, so I can't easily just take it out. But I understand if you don't/can't support PyPy with its small userbase, feel free to close the issue, I am raising it to make sure.

**Comment by reaperhulk** [comment]
Do you have a supported range of PyPy versions? Would `cryptography`'s choices be sufficiently broad (we ship pypy 3.7, 3.8, and 3.9 wheels right now I believe)? Could we just do 3.8 and 3.9?

**Comment by remram44** [comment]
I personally track the latest, so this would be sufficient for my tests to pass, but I am probably not the best person to answer this :smile:

Ubuntu 22.04 has 3.8, Debian 11 "bullseye" shipped this year has 3.7, Ubuntu 20.04 has 3.6.

**Comment by Alireza1379dev** [comment]
> It seems that there are no binary wheels for PyPy, and build from source now requires a Rust toolchain. This is a major problem for installation.
> 
> ```
> $ docker run -ti --rm pypy:3.9 bash
> 
> /# pip install -U pip
> Successfully installed pip-22.2.2
> 
> /# pip install bcrypt
> Collecting bcrypt
>   Downloading bcrypt-4.0.0.tar.gz (25 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... done
> Building wheels for collected packages: bcrypt
>   Building wheel for bcrypt (pyproject.toml) ... error
>   error: subprocess-exited-with-error
>   
>   × Building wheel for bcrypt (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [58 lines of output]
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build/lib.linux-x86_64-pypy39
>       creating build/lib.linux-x86_64-pypy39/bcrypt
>       copying src/bcrypt/__about__.py -> build/lib.linux-x86_64-pypy39/bcrypt
>       copying src/bcrypt/__init__.py -> build/lib.linux-x86_64-pypy39/bcrypt
>       running egg_info
>       writing src/bcrypt.egg-info/PKG-INFO
>       writing dependency_links to src/bcrypt.egg-info/dependency_links.txt
>       writing requirements to src/bcrypt.egg-info/requires.txt
>       writing top-level names to src/bcrypt.egg-info/top_level.txt
>       reading manifest file 'src/bcrypt.egg-info/SOURCES.txt'
>       reading manifest template 'MANIFEST.in'
>       warning: no previously-included files found matching 'requirements.txt'
>       warning: no previously-included files found matching 'release.py'
>       warning: no previously-included files found matching 'mypy.ini'
>       warning: no previously-included files matching '*' found under directory '.github'
>       warning: no previously-included files matching '*' found under directory '.circleci'
>       warning: no previously-included files found matching 'src/_bcrypt/target'
>       warning: no previously-included files matching '*' found under directory 'src/_bcrypt/target'
>       adding license file 'LICENSE'
>       writing manifest file 'src/bcrypt.egg-info/SOURCES.txt'
>       copying src/bcrypt/_bcrypt.pyi -> build/lib.linux-x86_64-pypy39/bcrypt
>       copying src/bcrypt/py.typed -> build/lib.linux-x86_64-pypy39/bcrypt
>       running build_ext
>       running build_rust
>       
>           =============================DEBUG ASSISTANCE=============================
>           If you are seeing a compilation error please try the following steps to
>           successfully install bcrypt:
>           1) Upgrade to the latest pip and try again. This will fix errors for most
>              users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
>           2) Ensure you have a recent Rust toolchain installed. bcrypt requires
>              rustc >= 1.56.0.
>       
>           Python: 3.9.12
>           platform: Linux-5.15.0-48-generic-x86_64-with-glibc2.31
>           pip: n/a
>           setuptools: 65.4.1
>           setuptools_rust: 1.5.2
>           rustc: n/a
>           =============================DEBUG ASSISTANCE=============================
>       
>       error: can't find Rust compiler
>       
>       If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
>       
>       To update pip, run:
>       
>           pip install --upgrade pip
>       
>       and then retry package installation.
>       
>       If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
>       
>       This package requires Rust >=1.56.0.
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for bcrypt
> Failed to build bcrypt
> ERROR: Could not build wheels for bcrypt, which is required to install pyproject.toml-based projects
> ```
> 
> Installing 3.2.2 works.

i have this problem

**Comment by remram44** [comment]
What problem? You can't install which version of bcrypt on which version of pypy? You can't have literally the same problem, because `bcrypt-4.0.1-pp39-pypy39_pp73-manylinux_2_28_x86_64.whl` was pushed to PyPI before this issue was closed.

**Comment by remram44** [comment]
Not only are you posting in a closed issue but you're not even using PyPy...

**Comment by Alireza1379dev** [comment]
> Not only are you posting in a closed issue but you're not even using PyPy...

what is the solution?
what should i do?
