### ISSUE TITLE
Include a wheel for linux_armv7l

### ISSUE THREAD

**Issue by MorganLindqvist** [pyca/bcrypt#442]
I have a number of armv7l based computers and currently I need to install the whole build environement on all of them to be able to use bcrypt.

The code builds fine but building on each platform and "polluting" the production devices with development packages is something I would like to avoid. Also a bigger risk that there is a difference between the binaries when building on each platform and trigger really hard to find bugs.

Could you include a wheel for linux armv7l?

/Morgan

**Comment by alex** [comment]
Unfortunately building/supporting armv7l wheels is currently impractical. https://github.com/pyca/cryptography/issues/6286 explains why.

Your best bet is probably https://piwheels.org/, which is nominally for Raspberry Pis, but I imagine should work with any armv7l CPU.
