### ISSUE TITLE
Rust Version more recent than stable branch for Debian

### ISSUE THREAD

**Issue by DomAmato** [pyca/bcrypt#453]
So the stable release for Debian is bullseye whose rustc version is 1.48 
https://packages.debian.org/search?searchon=names&keywords=rustc
![image](https://user-images.githubusercontent.com/6936055/200466496-72f3bb46-801e-4ccd-92fb-b74551ecf6da.png)

However bcrypt is requiring a newer version that would require building rust from source. I don't expect that the rust version would have to be pinned to the oldest stable linux version but debian is a relatively popular flavor of linux and if you want to install rust from the package manager it would not support bcrypts required version of rust.

I am doing this on a raspberry pi which is probably why its trying to build the wheel in the first place but just a thought that maybe the required version is too aggressive in its requirement.

```
running build_rust
[Build]   main                    =============================DEBUG ASSISTANCE=============================
[Build]   main                    If you are seeing a compilation error please try the following steps to
[Build]   main                    successfully install bcrypt:
[Build]   main                    1) Upgrade to the latest pip and try again. This will fix errors for most
[Build]   main                       users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
[Build]   main                    2) Ensure you have a recent Rust toolchain installed. bcrypt requires
[Build]   main                       rustc >= 1.56.0.
[Build]   main                    Python: 3.9.14
[Build]   main                    platform: Linux-5.4.0-1045-aws-armv7l-with-glibc2.31
[Build]   main                    pip: n/a
[Build]   main                    setuptools: 65.5.1
[Build]   main                    setuptools_rust: 1.5.2
[Build]   main                    rustc: 1.48.0
[Build]   main                    =============================DEBUG ASSISTANCE=============================
[Build]   main                error: Rust 1.48.0 does not match extension requirement >=1.56.0
```

**Comment by alex** [comment]
Unfortunately the rust library we use to provide bcrypt requires 1.56, so we're not able to lower the version.

We provide wheels for x86 and arm64 for this reason -- piwheels generally provides them for arm32, but unfortunately they themselves are having an issue at the moment preventing them from building rust packages.

**Comment by DomAmato** [comment]
I figured that was likely the case for why it was set to the version it is. 64 bit OS works fine so I am unblocked on what I was working on so you can probably close this issue.

**Comment by alex** [comment]
Ok. Sorry for the inconvenience, hopefully piwheels has their situation resolved soon.
