### ISSUE TITLE
hash comparison suddenly fails for two days then works normally is this possible?

### ISSUE THREAD

**Issue by mohas** [pyca/bcrypt#454]
Hi all, our hash comparison for auth mechanism on our website which was working for several months suddenly failed when using the same password, then succeeds after about two days, is something like this possible? I say it again there was not code or password change involved, maybe someone can shed a light on this matter.

more info: compareing the hashed password to an old stored hash failed while getting a new hash and comparing it succeeds

```
//this failed and causes our auth mechanism to fail, for two days then fixed by itself
await bcrypt.compare( //returns false for two days then true
            userPswd,
            databasePswd
        )
//made a unit test like this and there is no problem!
const testPswd = bcrypt.hashSync(userPswd, 10)
await bcrypt.compare( //returns true
            userPswd,
            testPswd 
        )
```

I don't know if this is a good idea but this is the hashes for completeness sake:
stored hash `$2b$12$5FhjippkEtkE6j0qFkjL9ub9sxSz5G3alQIEmQZIMe/9OjyRc4fJm`
generated hash `$2b$10$aVN5l/VgSi.5kunq3fNjruaw5j/RDsRb4/uop981sQsTdEDoJCd56`

I'm using node bcrypt v 5.1.0

**Comment by reaperhulk** [comment]
…are you using the Python bcrypt package at all? You mention node and a version that doesn’t match our versioning.

**Comment by mohas** [comment]
no I'm using the node version and I have posted there too, but I'm asking about the core bcrypt algorithm here, can this happen in bcrypt algorithm?

**Comment by reaperhulk** [comment]
The bcrypt hash contains information about work factor and salt so if you re-hash the same password it will have a different value each time (depending on the API), but it should always validate.

**Comment by mohas** [comment]
OK thank you, as I said it was a temporary failure, weird
