### ISSUE TITLE
PyPi hashes for bcrypt==3.2.0 don't match those from Pipfile.lock

### ISSUE THREAD

**Issue by tomasz-prtsr** [pyca/bcrypt#463]
I have `Pipfile.lock` from 2021, with `bcrypt==3.2.0` inside.

Recently I've tried installing from it, but `pipenv` failed with a hash mismatch error.

I've "cross-checked" everything and it turns out that PyPi contains some additional uploads for `bcrypt==3.2.0`, dated Dec 31, 2021:

https://pypi.org/project/bcrypt/3.2.0/#files

The possible explanation could be the following PR, merged on Dec 31, 2021:

https://github.com/pyca/bcrypt/pull/283 ("modernize the wheel builder")

--possibly along with the following Github Action: 

https://github.com/pyca/bcrypt/actions/runs/1641478934

Given that on Dec 31, 2021 `bcrypt==3.2.0` was the latest version, it seems plausible that  new deployment code would update its PyPi entry.

---

**My question is:**

Could you confirm that the additional files are legitimate (i.e. it was you who uploaded them/triggered the upload, on Dec 31, 2021)?

**Comment by alex** [comment]
Yes, these were intentional to offer wheels for more modern manylinux/musllinux standards.

**Comment by tomasz-prtsr** [comment]
Thank you!
