### ISSUE TITLE
testsuite absent

### ISSUE THREAD

**Issue by idella** [pyca/bcrypt#48]
The setup.py is filled with references to the testsuite and designates pytest as a test runner, despite the tests folder being absent from the tarball.

**Comment by frispete** [comment]
which prevents package builders from properly testing the build! 

Please include test code in tarball.

**Comment by danstender** [comment]
We build the Debian package (python-bcrypt) with the Pypi tarball (we prefer this because it's PGP signed) and would love to have the tests in that tarball.

**Comment by frispete** [comment]
@danstender: the github tarball is more an accident than anything else: I build openSUSE packages on OBS, and it has grown tests (for official packages) lately, that compare tarballs with official sources. In case of PyPI packages, those are usually built with sdist, while the github tarballs are just directory snapshots, that miss any custom sdist preparations (eggs, etc..).
