### ISSUE TITLE
sha digest can contain NUL bytes

### ISSUE THREAD

**Issue by hyperknot** [pyca/bcrypt#55]
1. website instructs to use sha512 digest for long password support
2. sha512 digest can contain NUL bytes
3. bcrypt breaks for some password, like: `asdasa`, whose sha512 digest contains a NUL byte

**Comment by reaperhulk** [comment]
Very good catch (and apologies for taking so long on responding to this!). The digest needs to be encoded to prevent null bytes, but doing something like encoding a 64 byte SHA512 hash will exceed the limit so either you accept some limited truncation there or switch to a shorter hash function. I'll put in a PR to update the docs on this front.

**Comment by alex** [comment]
Hex sha256 is a good compromise IMO

**Comment by hyperknot** [comment]
In the meantime I've reviewed this issue, and the solution for me was to use the passlib wrapper for bcrypt. passlib has a well tested built-in method called: `bcrypt_sha256`
https://pythonhosted.org/passlib/lib/passlib.hash.bcrypt_sha256.html

Implementation line:
https://bitbucket.org/ecollins/passlib/src/fa26802fc88fbc6b2d4b9676970bed7e6d53fc9d/passlib/handlers/bcrypt.py?at=default&fileviewer=file-view-default#bcrypt.py-677

**Comment by reaperhulk** [comment]
#57 addresses this.

**Comment by reaperhulk** [comment]
This appears to be resolved so I'll close this now. If there's still an issue feel free to reopen.
