### ISSUE TITLE
Describe in README the diff between bcrypt and py-bcrypt package

### ISSUE THREAD

**Issue by harobed** [pyca/bcrypt#6]
Hi,

can you append to README the diff between bcrypt and https://pypi.python.org/pypi/py-bcrypt ?

Best regards,
Stephane

**Comment by dstufft** [comment]
With bcrypt 3.1.0 we should be completely API compatible with py-bcrypt. There may be a few minor differences like what specific error gets raised where, but in general we should be a drop in I believe.
