### ISSUE TITLE
_crypt_blowfish_rn conflict

### ISSUE THREAD

**Issue by crazyh** [pyca/bcrypt#61]
I have faced the following issue:

When I run my Python application (which uses this bcrypt library) from shell and application calls bcrypt.hashpw with '2b' salt then all works OK.

But when I run the application under Apache then bcrypt.hashpw raises 'Invalid salt' exception.

After researching I found that there symbol name conflict occurred: Apache Portable Runtime has own _crypt_blowfish_rn function (http://svn.apache.org/repos/asf/apr/apr/trunk/crypto/crypt_blowfish.c) which does not support '2b' hashes and which called by crypt_rn because libapr-1.so.0 library was loaded before _bcrypt.so.

Possible solutions are:

- Use an unique prefix for public functions like _crypt_blowfish_rn to eliminate name conflict
- Make _crypt_blowfish_rn static and move it into the same C module where crypt_rn lives (wrapper.c)

Found on Apache 2.4.6, APR 1.4.8, CentOS 7, bcrypt 2.0.0

**Comment by reaperhulk** [comment]
Thanks for the report. No namespacing in C strikes again. The easiest fix is likely to be adding the unique prefix rather than trying to change the linking behavior (as the latter is different on many platforms). Do you have time to submit a PR for this?

**Comment by crazyh** [comment]
Done. See PR #62.

**Comment by cwalkatron** [comment]
+1

**Comment by SeanPlusPlus** [comment]
+1

**Comment by reaperhulk** [comment]
The PR has been merged and I'll be doing a release this week with it. Apologies for the slow response :(
