### ISSUE TITLE
checkpw issue, I need some guide. 

### ISSUE THREAD

**Issue by razeta** [pyca/bcrypt#628]
Hello. 

I have this issue, I been searching and I try everything I could find, but the issue persist. bcrypt.checkpw return false even when password is correct. In my database I have this in 

hashed password: $2b$14$pQOcw.eOoood3v7svmIZt.3lhBjyHYfCoJB4jbaRqPGQvwI4iosGG 
raw password: "test101".

If I do the hashing and the checkpw in the same function, it works. But when I split the 2, hashing in register and checkpw in login. Then, It does not matter what I do, I can't make it return True. The password is the same as the one used in hashing. The database has the records stored correctly.

This is what is being printed in login and use as input for the checkpw function: 
hashed_password 
<class 'bytes'> 
b'$2b$14$pQOcw.eOoood3v7svmIZt.3lhBjyHYfCoJB4jbaRqPGQvwI4iosGG' 
b'test101'

Here are the register and login functions, Im using streamlit for UI and SQLite3 for database.

```
# Función de registrar
def register(database, nombre, password, email, matricula):
    try:
        conn = database.connect()
        cursor = conn.cursor()

        query = "INSERT INTO student (nombre, password, email, matricula, created_at, active) VALUES (?, ?, ?, ?, ?, ?)"
        cursor.execute(query, (nombre,
                               bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt(14)),
                               email,
                               matricula,
                               datetime.now(),
                               True))
        conn.commit()

    except Exception as e:
        print(f"Error: {e}")
        return False

    finally:
        conn.close()

    return True


# Función de login
def login(database, email, password):
    try:
        conn = database.connect()
        cursor = conn.cursor()

        query = "SELECT password FROM student WHERE email = ?"
        cursor.execute(query, (email,))

        hashed_password = cursor.fetchone()

        if hashed_password:
            print("hashed_password")
            print(type(hashed_password[0]))  # Debería imprimir <class 'bytes'>
            print(hashed_password[0])  # Debería imprimir el hash en formato bytes
            print(password.encode('utf-8'))  # Debería imprimir el hash en formato bytes
            if bcrypt.checkpw(password.encode('utf-8'), hashed_password[0]):
                return True

    except Exception as e:
        print(f"Error: {e}")

    finally:
        conn.close()

    return False

Here is the table:

 cursor.execute('''
            CREATE TABLE IF NOT EXISTS student (
                id INTEGER PRIMARY KEY,
                email TEXT NOT NULL UNIQUE,
                matricula INTEGER NOT NULL UNIQUE,
                nombre TEXT NOT NULL,
                password TEXT NOT NULL,
                created_at DATETIME NOT NULL,
                active BOOLEAN NOT NULL,
                is_admin BOOLEAN NULLABLE              
            )
        ''')
```

**Comment by alex** [comment]
Can you please provide a self-contained example we can run ourselves to reproduce this issue?

**Comment by razeta** [comment]
Hello. I was doing what you requested. And it worked fine in another computer. Then I replicated the test in my work computer and It worked, then I try it again on my project and it worked! :S I have no idea what happend... I believe it was a cache problem with libs maybe, I don't know yet. If I have more information available, I will shared it. Thanks.

**Comment by alex** [comment]
Given this, I'm going to close this issue for now.

**Comment by razeta** [comment]
Hello, I found my problem. 

I was using to different hashing system. In my old system I was using 

`hashed_password = stauth.Hasher([password]).generate(),`

to hash my password, before sending it to new system using my register() and checkpw using bcrypt.

So, I was double hashing, that's why checkpw did not return True. It didn't had the correct hash when validating. 

So, when dealing with this issue, verify first if your not hashing with another function your password. 

Thanks.
