### ISSUE TITLE
Python2.7  ImportError: cannot import name _bcrypt

### ISSUE THREAD

**Issue by Numb523** [pyca/bcrypt#640]
I ran the project on the Centos 7.7 GTR-PYTHON third-party automated test framework executor and saw this error when "import bcrypt". But when I run "import bcrypt" in native Pycharm, it reports no error. I use Python 2.7, so the latest version of brcypt is 3.1.7. How can I solve this problem?

**Comment by alex** [comment]
We no longer support Python 2.7, or versions of bcrypt that old, so you're going to be on your own.

The answer will almost certainly involve a corrupted installation. I recommend you install all packages into a virtualenv environment.

**Comment by Numb523** [comment]
这是来自QQ邮箱的自动回复邮件。邮件已收到，一般不会登陆邮箱查看，如果是重要邮件，请微信或者qq联系我及时查看

**Comment by Numb523** [comment]
这是来自QQ邮箱的自动回复邮件。邮件已收到，一般不会登陆邮箱查看，如果是重要邮件，请微信或者qq联系我及时查看
