### ISSUE TITLE
python 3.7.3

### ISSUE THREAD

**Issue by ahmednreldin** [pyca/bcrypt#657]
I can't install version [4.0.1] on python 3.7.3 

is the package supported on that version

the below error appears when installing it using dpkg 

```
dpkg: dependency problems prevent configuration of python3-bcrypt:
 python3-bcrypt depends on python3 (<< 3.7); however:
  Version of python3 on system is 3.7.3-1. 
```

i don't want to install it using pip

**Comment by alex** [comment]
Please provide instructions for reproducing this issue from a fresh system.

**Comment by reaperhulk** [comment]
We release to pypi and support installation through pip. This looks like an issue with the deb package and we can’t help with that since we didn’t create it.

**Comment by ahmednreldin** [comment]
to reproduce the issue

### dowload package as wheel
`pip3 wheel bcrypt`

#### convert wheel to debian 
```
wheel2deb 
wheel2deb build
```

### install package on Debian distro
`dpkg -i bcrypt.deb` # here throw the error

**Comment by reaperhulk** [comment]
This is not an issue with this package, but rather something in the metadata generated by wheel2deb. We cannot help with tools like this and you should look at how that software creates the package.
