### ISSUE TITLE
New release results in bcrypt break

### ISSUE THREAD

**Issue by Stefanhg** [pyca/bcrypt#677]
Hello,

Our system sadly relies on tip of bcrypt and in this case the new release breaks when you do
`import bcrypt`
Can anyone fix this? I don't know what this package does except that it is used in some dependable packages.

**Comment by Stefanhg** [comment]
After more digging it is actually not our systems but the package Paramiko with bcrypt>=3.2 
https://github.com/paramiko/paramiko/blob/main/setup.py
But i would still assume that `import bcrypt` is expected to work.

**Comment by alex** [comment]
Can you explain what "breaks" means?

**Comment by Stefanhg** [comment]
```
>>> import bcrypt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\shg\venv\lib\site-packages\bcrypt\__init__.py", line 13, in <module>
    from ._bcrypt import (
ModuleNotFoundError: No module named 'bcrypt._bcrypt'
```

**Comment by Stefanhg** [comment]
The 4.0.1 release includes the following files: __about__.py, __init__.py, _bcrypt.pyd, _bcrypt.pyi, py.typed
The 4.1.0 release includes the following files: __init__.py, __init.pyi, _bcrypt.cp37-win_amd64.pyd, py.typed

Seems like something has gone wrong when the release has happened. Some files are missing.

**Comment by alex** [comment]
I'm not able to reproduce:

```
(tempenv-3ce71814330fc) ~ ❯❯❯ pip install bcrypt
Collecting bcrypt
  Downloading bcrypt-4.1.0-cp37-abi3-macosx_13_0_universal2.whl.metadata (9.2 kB)
Downloading bcrypt-4.1.0-cp37-abi3-macosx_13_0_universal2.whl (528 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 528.2/528.2 kB 5.5 MB/s eta 0:00:00
Installing collected packages: bcrypt
Successfully installed bcrypt-4.1.0
(tempenv-3ce71814330fc) ~ ❯❯❯ python3 -c "import bcrypt"
(tempenv-3ce71814330fc) ~ ❯❯❯ 
```

Can you provide more steps to reproduce?

**Comment by Stefanhg** [comment]
Maybe it is a Windows-specific thing? 
If you go into the folder where bcrypt is installed. Do you have the same files as me:
` __init__.py, __init.pyi, _bcrypt.cp37-win_amd64.pyd, py.typed`

**Comment by strickvl** [comment]
I get the same error here https://github.com/zenml-io/zenml/actions/runs/7007131635/job/19060516311#step:4:2556

**Comment by alex** [comment]
Hmm, I don't see how this could ever have worked: https://github.com/pyca/bcrypt/blob/4.0.1/src/bcrypt/__init__.py#L72-L74 (that's what it looks like in the previous release)

**Comment by f1shl** [comment]
Same error for me, using paramiko.

**Comment by kgriffs** [comment]
Thanks @reaperhulk ! This broke one of our apps at work as well; appreciate the rapid response.

**Comment by cvubrugier** [comment]
Thank you @reaperhulk for your prompt reply.
The pipeline of an application I maintain at broken was broken since bcrypt release 4.1.0 (the unit tests failed).
I see that our build pipeline is back to normal.

**Comment by Stefanhg** [comment]
Thank you  @reaperhulk  for pulling back the release!

**Comment by gitta-jfrog** [comment]
Hi @reaperhulk 

Can you add a reason for the "data-yanked" field of version 4.1.0?
Unfortunately, following the pulling back of 4.1.0, Artifactory failed to detect this version as yanked as the value is empty and continued to serve it as the latest version.

It will be highly appreciated if that change is possible.
Thanks!

**Comment by alex** [comment]
I've gone ahead and done so.

(It was a bit fraught, because the only way to do so was to un-yank for a second. Hopefully this didn't disturb anyone!)
