### ISSUE TITLE
Build is failing on Alpine Linux & Python 3.5

### ISSUE THREAD

**Issue by rudyryk** [pyca/bcrypt#77]
I get a build error with the latest `bcrypt` release on Alpine Linux and Python 3.5:

```c
src/_csrc/bcrypt_pbkdf.c: In function 'bcrypt_pbkdf':
src/_csrc/bcrypt_pbkdf.c:137:3: warning: implicit declaration of function 'bcrypt_hash' [-Wimplicit-function-declaration]
   bcrypt_hash(sha2pass, sha2salt, tmpout);
   ^
error: command 'gcc' failed with exit status 1
```

The complete output and the Dockerfile are attached. To reproduce the error you may run (after placing Dockerfile.txt to the same dir):

```
docker build . -f Dockerfile.txt -t bcrypt-test
```

[error-output.txt](https://github.com/pyca/bcrypt/files/337931/error-output.txt)
[Dockerfile.txt](https://github.com/pyca/bcrypt/files/337929/Dockerfile.txt)

**Comment by reaperhulk** [comment]
@rudyryk Thanks for the report. I'll test this tonight and get a fix up.

**Comment by reaperhulk** [comment]
#79 should resolve this issue (tested in the alpine docker image)

**Comment by rudyryk** [comment]
@reaperhulk Great. I confirm, it's building successfully now. Thank you! :)

**Comment by dstufft** [comment]
Closing this as it's resolved in master and will be fixed in the upcoming 3.1.0 release.

**Comment by mixmastamyk** [comment]
How can I install python-bcrypt on alpine linux without compiling it? 

First thing I do is upgrade pip to (currently) 9.0.1, but it does not find the wheels for bcrypt and cffi.  It does install other wheels, so not sure what the difference is.

**Comment by reaperhulk** [comment]
The difference is this wheel has binary data in it. alpine linux is not manylinux1 compatible so you have to compile it yourself -- there's no choice.

**Comment by mixmastamyk** [comment]
IC, thanks.

**Comment by arpithpm** [comment]
Hello,
I'm facing issues on running a container when I include the flask-bcrypt. I see this thread addresses the same issue. Could anyone suggest the workaround for this?
Thanks
