### ISSUE TITLE
Release 3.1.0

### ISSUE THREAD

**Issue by reaperhulk** [pyca/bcrypt#82]
Checklist:

- [x] Merge #81 
- [x] Merge #79 
- [x] Merge #76 
- [x] Merge #75 
- [x] Merge #84
- [x] Merge #86
- [x] Merge #87 
- [x] Update changelog to note the wraparound compatibility fix + alpine linux compile fix + word the `checkpw` addition better
- [x] Update version to 3.1.0

**Comment by zachary822** [comment]
I am getting this warning:
```
venv/lib/python3.5/site-packages/bcrypt/__init__.py:51: UserWarning: implicit cast to 'char *' from a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  _bcrypt.lib.encode_base64(output, salt, len(salt))
```

**Comment by reaperhulk** [comment]
You don't need to worry about it for now as it's a warning just added in cffi 1.8.3 (released today). We'll issue a bcrypt 3.1.1 soon-ish to resolve the warning though. (Also I should close this issue since we released 3.1.0 quite awhile ago)

**Comment by reaperhulk** [comment]
@zachary822 3.1.1 is now released and should resolve the warning!

**Comment by zachary822** [comment]
Thanks! It does.
