### ISSUE TITLE
README.rst contains a non ascii character causing install failure with Python 3.5 Ubuntu

### ISSUE THREAD

**Issue by UTAS-Nick-Howden** [pyca/bcrypt#83]
The tick in the string    ........   (if you're not using pypy)
is not an ascii tick but is \xe2 \x80 \x99

This causes the error 
  File "/tmp/easy_install-dd0xuxvq/bcrypt-3.0.0/setup.py", line 195, in <module>
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 521: ordinal not in range(128)

**Comment by reaperhulk** [comment]
You can fix this by setting your shell LC_ALL to a UTF8 locale, but this has been corrected in master as well and won't be present in the next release.

**Comment by pypingou** [comment]
> won't be present in the next release.

Won't or will?

**Comment by reaperhulk** [comment]
Not the clearest phrasing I suppose. The unicode character has been removed.

**Comment by dstufft** [comment]
Closing this as it is resolved in master and will be fixed in the 3.1.0 release.
