### ISSUE TITLE
4.1.3 generates errors; downgrading to 4.1.2 is fine

### ISSUE THREAD

**Issue by BrainAnnex** [pyca/bcrypt#835]
The error is: 
`ImportError: DLL load failed while importing _bcrypt: The specified procedure could not be found`

This error seems to crop up from time to time, according to the following thread:
https://stackoverflow.com/questions/77696374/how-to-fix-importerror-dll-load-failed-while-importing-bcrypt-the-specified/78762744#78762744

Several people say how downgrading `bcrypt` solved their problem...

Indeed, I had that same error with 4.1.3 !  Downgrading to 4.1.2 made it go away.

I'm using a venv, with python 3.8 , on Windows.

**Comment by reaperhulk** [comment]
This can be multiple issues. In the linked  likely they need to upgrade python as 3.9.0 and 3.9.1 had a bug. Later 3.9.x releases should work.

You’ll also see this error if you’re running on Windows 7, which is no longer supported by the compiler we use to generate binary wheels.

**Comment by BrainAnnex** [comment]
Aha, mystery solved, thanks!  Yes, indeed I'm still on Windows 7 (hence the python 3.8)... not for much longer - but still.
