### ISSUE TITLE
hashpw() is silently converting 2y -> 2b

### ISSUE THREAD

**Issue by eli-collins** [pyca/bcrypt#85]
As of 3.0.0, `hashpw()` is converting 2y -> 2b hashes.   For example:

    >>> import bcrypt
    >>> print(bcrypt.hashpw("test", b"$2y$04$5BJqKfqMQvV7nS.yUguNcueVirQqDBGaLXSqj.rs.pZPlNR0UX/HK"))
    b"$2b$04$5BJqKfqMQvV7nS.yUguNcueVirQqDBGaLXSqj.rs.pZPlNR0UX/HK")

For any code that's doing verification via `hmac.compare_digest(hashpw(secret, hash), hash)`, this will result in 2y hashes *never* verifying correctly.

I was expecting to either get a 2y hash back, or have `hashpw()` throw an "invalid salt" error.

**Comment by reaperhulk** [comment]
This is fixed by #84  :)

**Comment by reaperhulk** [comment]
Once that merges we'll be doing a 3.1.0 release with the new features + bug fixes that cropped up from the rewrite. Thanks for the report!

**Comment by eli-collins** [comment]
Ah, thanks! My apologies, thought I'd searched all the issues, missed the glaringly open PR :)

**Comment by dstufft** [comment]
Fixed in master now!
