### ISSUE TITLE
Suggestion: Adding link to scrypt docs

### ISSUE THREAD

**Issue by githubUser982** [pyca/bcrypt#860]
Suggestion:
Since index.md suggests that you should use scrypt instead, perhaps it could link to nodes scrypt docs: https://nodejs.org/api/crypto.html#crypto_crypto_scrypt_password_salt_keylen_options_callback
Otherwise new users, that may think everything good is a module, may install node-scrypt which already recommends using crypto.scrypt instead.

I believe the rst markdown would be:
> `scrypt <https://nodejs.org/api/crypto.html#crypto_crypto_scrypt_password_salt_keylen_options_callback>`_

Thank you for your time.

**Comment by reaperhulk** [comment]
This is a Python module, linking to node docs would not make sense

**Comment by githubUser982** [comment]
Oh... So sorry. got the wrong module
