### ISSUE TITLE
I get 'node-gyp rebuild' failed on your system. "Tell the author"

### ISSUE THREAD

**Issue by dauledk** [pyca/bcrypt#91]
I was trying to install bcrypt on windows 8 with the following command:

`npm install bcrypt --python=\Python27\python.exe`

But it failed. I have attached the log file. 

[npm-debug.txt](https://github.com/pyca/bcrypt/files/397084/npm-debug.txt)

**Comment by alex** [comment]
This is the python bcrypt package, not the node bcrypt package.
