### ISSUE TITLE
faster with hashpw or checkpw

### ISSUE THREAD

**Issue by adityosnrost** [pyca/bcrypt#96]
Hi,

I would like know if there is a way to do hashpw or checkpw faster. I am beginner in hashing and encryption thing, and would like to learn it. This is my current code:
`encodedPassword = str(userAuthInfo['password']).encode('utf-8')`
`db1start = datetime.datetime.now()`
`check= bcrypt.checkpw(encodedPassword, DBHashedPassword.encode('utf-8'))`
`print((datetime.datetime.now() - db1start).microseconds)`

from a couple of trial, it took around 400 milliseconds  - 600 milliseconds to do it, is there a way to do it faster ? 
How long for a Restful app for login function time is acceptable ?
Thank you

**Comment by alex** [comment]
`bcrypt` is slow by design: https://codahale.com/how-to-safely-store-a-password/
